// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: ui_main_screen

#ifndef _UI_MAIN_SCREEN_UI_H
#define _UI_MAIN_SCREEN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_background_px_png);    // assets/background_px.png
LV_IMG_DECLARE(ui_img_solgan_px_png);    // assets/solgan_px.png
LV_IMG_DECLARE(ui_img_terminal_icon_px_png);    // assets/terminal_icon_px.png
LV_IMG_DECLARE(ui_img_lightbulb_px_png);    // assets/lightbulb_px.png
LV_IMG_DECLARE(ui_img_button_icon_px_png);    // assets/button_icon_px.png
LV_IMG_DECLARE(ui_img_lux_icon_px_png);    // assets/lux_icon_px.png
LV_IMG_DECLARE(ui_img_co2_icon_px_png);    // assets/co2_icon_px.png
LV_IMG_DECLARE(ui_img_fan_icon_2_px_png);    // assets/fan_icon_2_px.png
LV_IMG_DECLARE(ui_img_humidity_icon_px_png);    // assets/humidity_icon_px.png
LV_IMG_DECLARE(ui_img_tempurate_2_px_png);    // assets/tempurate_2_px.png
LV_IMG_DECLARE(ui_img_water_management_symbol_px_png);    // assets/water management symbol_px.png
LV_IMG_DECLARE(ui_img_hummid_soild_icon_px_png);    // assets/hummid_soild_icon_px.png

// FONTS
LV_FONT_DECLARE(ui_font_arialbold16);
LV_FONT_DECLARE(ui_font_arialbold24);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
