// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: ui_main_screen

#ifndef _UI_MAIN_SCREEN_UI_H
#define _UI_MAIN_SCREEN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_background_px_png);    // assets/background_px.png
LV_IMG_DECLARE(ui_img_figma_logo_px_png);    // assets/Figma_logo_px.png
LV_IMG_DECLARE(ui_img_figma_terminal_px_png);    // assets/Figma_terminal_px.png
LV_IMG_DECLARE(ui_img_figma_button_px_png);    // assets/Figma_button_px.png
LV_IMG_DECLARE(ui_img_figma_lightbulbs_px_png);    // assets/Figma_lightbulbs_px.png
LV_IMG_DECLARE(ui_img_figma_lux_px_png);    // assets/Figma_lux_px.png
LV_IMG_DECLARE(ui_img_figma_co2_px_png);    // assets/Figma_co2_px.png
LV_IMG_DECLARE(ui_img_figma_fans_px_png);    // assets/Figma_fans_px.png
LV_IMG_DECLARE(ui_img_figma_humidity_px_png);    // assets/Figma_humidity_px.png
LV_IMG_DECLARE(ui_img_figma_tempt_px_png);    // assets/Figma_tempt_px.png
LV_IMG_DECLARE(ui_img_figma_water_px_png);    // assets/Figma_water_px.png
LV_IMG_DECLARE(ui_img_figma_soild_humid_px_png);    // assets/Figma_soild_humid_px.png

// FONTS
LV_FONT_DECLARE(ui_font_arialbold16);
LV_FONT_DECLARE(ui_font_arialbold24);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
