// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: ui_main_screen

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_uiPannelBackgound;
extern lv_obj_t * ui_Iloveptit;
extern void ui_event_uiTerminal(lv_event_t * e);
extern lv_obj_t * ui_uiTerminal;
extern lv_obj_t * ui_uiPannelLight;
extern lv_obj_t * ui_uiLabelLight;
extern lv_obj_t * ui_uiButtonLight;
extern lv_obj_t * ui_uiLightbulb;
extern lv_obj_t * ui_uiPannelLuxandCO2;
extern lv_obj_t * ui_uiValueLux;
extern lv_obj_t * ui_uiValueCO2;
extern lv_obj_t * ui_uiLabelPPM;
extern lv_obj_t * ui_uiLabelLux;
extern lv_obj_t * ui_uiImageLux;
extern lv_obj_t * ui_uiImageCO2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_uiFan;
extern lv_obj_t * ui_ImgButton3;
extern lv_obj_t * ui_uiPannelHumidandTemp;
extern lv_obj_t * ui_uiValueTemp;
extern lv_obj_t * ui_uiValueHumid;
extern lv_obj_t * ui_uiLabelHumid;
extern lv_obj_t * ui_uiLabelTemp;
extern lv_obj_t * ui_uiImageHumid;
extern lv_obj_t * ui_uiImageTemp;
extern lv_obj_t * ui_uiPannelWater;
extern lv_obj_t * ui_uiLabelWater;
extern lv_obj_t * ui_uiImageWater;
extern lv_obj_t * ui_uiButtonWater;
extern lv_obj_t * ui_uiPannelSoild;
extern lv_obj_t * ui_uiValueSoild;
extern lv_obj_t * ui_uiLabelSoild;
extern lv_obj_t * ui_uiImageSoild;
extern lv_obj_t * ui_uiPannelTerminal;
extern lv_obj_t * ui_uiTextTerminal;
// CUSTOM VARIABLES
extern lv_obj_t * uic_uiPannelBackgound;
extern lv_obj_t * uic_Iloveptit;
extern lv_obj_t * uic_uiTerminal;
extern lv_obj_t * uic_uiPannelLight;
extern lv_obj_t * uic_uiLabelLight;
extern lv_obj_t * uic_uiButtonLight;
extern lv_obj_t * uic_uiLightbulb;
extern lv_obj_t * uic_uiPannelLuxandCO2;
extern lv_obj_t * uic_uiValueLux;
extern lv_obj_t * uic_uiValueCO2;
extern lv_obj_t * uic_uiLabelPPM;
extern lv_obj_t * uic_uiLabelLux;
extern lv_obj_t * uic_uiImageLux;
extern lv_obj_t * uic_uiImageCO2;
extern lv_obj_t * uic_uiFan;
extern lv_obj_t * uic_uiPannelHumidandTemp;
extern lv_obj_t * uic_uiValueTemp;
extern lv_obj_t * uic_uiValueHumid;
extern lv_obj_t * uic_uiLabelHumid;
extern lv_obj_t * uic_uiLabelTemp;
extern lv_obj_t * uic_uiImageHumid;
extern lv_obj_t * uic_uiImageTemp;
extern lv_obj_t * uic_uiPannelWater;
extern lv_obj_t * uic_uiButtonWater;
extern lv_obj_t * uic_uiPannelSoild;
extern lv_obj_t * uic_uiValueSoild;
extern lv_obj_t * uic_uiLabelSoild;
extern lv_obj_t * uic_uiImageSoild;
extern lv_obj_t * uic_uiTextTerminal;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

