[env:esp_touch_lcd_screen]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

upload_speed = 921600
monitor_speed = 115200

; --- BẬT BỘ NHỚ FLASH 8MB & OCTAL PSRAM 8MB (BẮT BUỘC CHO MÀN 7 INCH) ---
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi      ; Kích hoạt Flash QIO + Octal PSRAM OPI

; --- CỜ BIÊN DỊCH BẮT BUỘC ---
build_flags = 
    -D BOARD_HAS_PSRAM                         ; Cho phép LVGL cấp phát Framebuffer trên PSRAM
    -D ARDUINO_USB_CDC_ON_BOOT=0          ; Bật Serial Monitor qua cổng USB Native
    -D ARDUINO_USB_MODE=1
    -D CORE_DEBUG_LEVEL=1
    -I include
    -I src
    -I lib
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -D DISABLE_ALL_LIBRARY_WARNINGS

; --- THƯ VIỆN ĐỒ HỌA ---
lib_deps = 
    lvgl/lvgl @ 8.3.11
    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git#v1.0.4
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.1
	https://github.com/esp-arduino-libs/esp-lib-utils.git#v0.3.0    
	knolleary/PubSubClient @ 2.8
    bblanchon/ArduinoJson @ 7.4.3
