// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: ui_main_screen

#include "ui.h"

lv_obj_t * uic_uiTextTerminal;
lv_obj_t * uic_uiImageSoild;
lv_obj_t * uic_uiLabelSoild;
lv_obj_t * uic_uiValueSoild;
lv_obj_t * uic_uiPannelSoild;
lv_obj_t * uic_uiButtonWater;
lv_obj_t * uic_uiPannelWater;
lv_obj_t * uic_uiImageTemp;
lv_obj_t * uic_uiImageHumid;
lv_obj_t * uic_uiLabelTemp;
lv_obj_t * uic_uiLabelHumid;
lv_obj_t * uic_uiValueHumid;
lv_obj_t * uic_uiValueTemp;
lv_obj_t * uic_uiPannelHumidandTemp;
lv_obj_t * uic_uiImageCO2;
lv_obj_t * uic_uiImageLux;
lv_obj_t * uic_uiLabelLux;
lv_obj_t * uic_uiLabelPPM;
lv_obj_t * uic_uiValueCO2;
lv_obj_t * uic_uiValueLux;
lv_obj_t * uic_uiPannelLuxandCO2;
lv_obj_t * uic_uiButtonLight;
lv_obj_t * uic_uiImageLight;
lv_obj_t * uic_uiLabelLight;
lv_obj_t * uic_uiPannelLight;
lv_obj_t * uic_uiTerminal;
lv_obj_t * uic_uiIhatePtit;
lv_obj_t * uic_uiIlovePtit;
lv_obj_t * uic_uiLogoPtit;
lv_obj_t * uic_uiPannelSolgan;
lv_obj_t * uic_uiPannelBackgound;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_uiPannelBackgound = NULL;
lv_obj_t * ui_uiPannelSolgan = NULL;
lv_obj_t * ui_uiLogoPtit = NULL;
lv_obj_t * ui_uiIlovePtit = NULL;
lv_obj_t * ui_uiIhatePtit = NULL;
lv_obj_t * ui_uiTerminal = NULL;
lv_obj_t * ui_uiPannelLight = NULL;
lv_obj_t * ui_uiLabelLight = NULL;
lv_obj_t * ui_uiImageLight = NULL;
lv_obj_t * ui_uiButtonLight = NULL;
lv_obj_t * ui_uiPannelLuxandCO2 = NULL;
lv_obj_t * ui_uiValueLux = NULL;
lv_obj_t * ui_uiValueCO2 = NULL;
lv_obj_t * ui_uiLabelPPM = NULL;
lv_obj_t * ui_uiLabelLux = NULL;
lv_obj_t * ui_uiImageLux = NULL;
lv_obj_t * ui_uiImageCO2 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_ImgButton3 = NULL;
lv_obj_t * ui_uiPannelHumidandTemp = NULL;
lv_obj_t * ui_uiValueTemp = NULL;
lv_obj_t * ui_uiValueHumid = NULL;
lv_obj_t * ui_uiLabelHumid = NULL;
lv_obj_t * ui_uiLabelTemp = NULL;
lv_obj_t * ui_uiImageHumid = NULL;
lv_obj_t * ui_uiImageTemp = NULL;
lv_obj_t * ui_uiPannelWater = NULL;
lv_obj_t * ui_uiLabelWater = NULL;
lv_obj_t * ui_uiImageWater = NULL;
lv_obj_t * ui_uiButtonWater = NULL;
lv_obj_t * ui_uiPannelSoild = NULL;
lv_obj_t * ui_uiValueSoild = NULL;
lv_obj_t * ui_uiLabelSoild = NULL;
lv_obj_t * ui_uiImageSoild = NULL;
lv_obj_t * ui_uiPannelTerminal = NULL;
lv_obj_t * ui_uiTextTerminal = NULL;
// event funtions
void ui_event_uiTerminal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_uiPannelTerminal, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_background_px_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Screen1, lv_color_hex(0x00FF66), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_Screen1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_uiPannelBackgound = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_uiPannelBackgound, lv_pct(100));
    lv_obj_set_height(ui_uiPannelBackgound, lv_pct(100));
    lv_obj_set_align(ui_uiPannelBackgound, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiPannelBackgound, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiPannelBackgound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uiPannelBackgound, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiPannelBackgound, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_uiPannelBackgound, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiPannelBackgound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiPannelSolgan = lv_obj_create(ui_Screen1);
    lv_obj_set_height(ui_uiPannelSolgan, 100);
    lv_obj_set_width(ui_uiPannelSolgan, lv_pct(100));
    lv_obj_set_x(ui_uiPannelSolgan, 0);
    lv_obj_set_y(ui_uiPannelSolgan, -215);
    lv_obj_set_align(ui_uiPannelSolgan, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiPannelSolgan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uiPannelSolgan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLogoPtit = lv_img_create(ui_uiPannelSolgan);
    lv_img_set_src(ui_uiLogoPtit, &ui_img_images_px_no_bg_png);
    lv_obj_set_width(ui_uiLogoPtit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLogoPtit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLogoPtit, -354);
    lv_obj_set_y(ui_uiLogoPtit, 10);
    lv_obj_set_align(ui_uiLogoPtit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiLogoPtit, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_uiLogoPtit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiIlovePtit = lv_label_create(ui_uiPannelSolgan);
    lv_obj_set_width(ui_uiIlovePtit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiIlovePtit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiIlovePtit, -29);
    lv_obj_set_y(ui_uiIlovePtit, 0);
    lv_obj_set_align(ui_uiIlovePtit, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_uiIlovePtit, "HỌC VIỆN CÔNG NGHỆ BƯU CHÍNH VIỄN THÔNG");
    lv_label_set_text(ui_uiIlovePtit, "HOC VIEN CONG NGHE BUU CHINH VIEN THONG");
    lv_obj_set_style_text_color(ui_uiIlovePtit, lv_color_hex(0xF30707), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiIlovePtit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiIlovePtit, &ui_font_arialbold24, LV_PART_MAIN | LV_STATE_DEFAULT);  //  &ui_font_arialbold24

    ui_uiIhatePtit = lv_label_create(ui_uiPannelSolgan);
    lv_obj_set_width(ui_uiIhatePtit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiIhatePtit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiIhatePtit, -114);
    lv_obj_set_y(ui_uiIhatePtit, 22);
    lv_obj_set_align(ui_uiIhatePtit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiIhatePtit, "Posts and Telecommunications Institute of Technology");

    ui_uiTerminal = lv_imgbtn_create(ui_uiPannelSolgan);
    lv_imgbtn_set_src(ui_uiTerminal, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_terminal_icon_px_png, NULL);
    lv_imgbtn_set_src(ui_uiTerminal, LV_IMGBTN_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_uiTerminal, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_uiTerminal, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_uiTerminal, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_uiTerminal, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_uiTerminal, 65);
    lv_obj_set_height(ui_uiTerminal, 65);
    lv_obj_set_x(ui_uiTerminal, 363);
    lv_obj_set_y(ui_uiTerminal, 12);
    lv_obj_set_align(ui_uiTerminal, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiTerminal, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_uiPannelLight = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_uiPannelLight, 200);
    lv_obj_set_height(ui_uiPannelLight, 185);
    lv_obj_set_x(ui_uiPannelLight, -292);
    lv_obj_set_y(ui_uiPannelLight, -59);
    lv_obj_set_align(ui_uiPannelLight, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiPannelLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiPannelLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiPannelLight, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiPannelLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelLight = lv_label_create(ui_uiPannelLight);
    lv_obj_set_width(ui_uiLabelLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelLight, -6);
    lv_obj_set_y(ui_uiLabelLight, 90);
    lv_obj_set_align(ui_uiLabelLight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelLight, "Light\n");
    lv_obj_set_style_text_color(ui_uiLabelLight, lv_color_hex(0x17DD19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelLight, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiImageLight = lv_img_create(ui_uiPannelLight);
    lv_img_set_src(ui_uiImageLight, &ui_img_lightbulb_px_png);
    lv_obj_set_width(ui_uiImageLight, 110);
    lv_obj_set_height(ui_uiImageLight, 110);
    lv_obj_set_x(ui_uiImageLight, -8);
    lv_obj_set_y(ui_uiImageLight, -12);
    lv_obj_set_align(ui_uiImageLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiImageLight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_uiImageLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiButtonLight = lv_imgbtn_create(ui_uiPannelLight);
    lv_imgbtn_set_src(ui_uiButtonLight, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_icon_px_png, NULL);
    lv_imgbtn_set_src(ui_uiButtonLight, LV_IMGBTN_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_uiButtonLight, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_uiButtonLight, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_uiButtonLight, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_uiButtonLight, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_uiButtonLight, 35);
    lv_obj_set_height(ui_uiButtonLight, 35);
    lv_obj_set_x(ui_uiButtonLight, 77);
    lv_obj_set_y(ui_uiButtonLight, -68);
    lv_obj_set_align(ui_uiButtonLight, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiButtonLight, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_uiPannelLuxandCO2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_uiPannelLuxandCO2, 200);
    lv_obj_set_height(ui_uiPannelLuxandCO2, 185);
    lv_obj_set_x(ui_uiPannelLuxandCO2, -292);
    lv_obj_set_y(ui_uiPannelLuxandCO2, 132);
    lv_obj_set_align(ui_uiPannelLuxandCO2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiPannelLuxandCO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiPannelLuxandCO2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiPannelLuxandCO2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiPannelLuxandCO2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiValueLux = lv_label_create(ui_uiPannelLuxandCO2);
    lv_obj_set_width(ui_uiValueLux, 50);
    lv_obj_set_height(ui_uiValueLux, 29);
    lv_obj_set_x(ui_uiValueLux, 20);
    lv_obj_set_y(ui_uiValueLux, -19);
    lv_obj_set_align(ui_uiValueLux, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiValueLux, "0.0\n");
    lv_obj_set_style_text_color(ui_uiValueLux, lv_color_hex(0xDD6C17), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiValueLux, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiValueLux, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiValueCO2 = lv_label_create(ui_uiPannelLuxandCO2);
    lv_obj_set_width(ui_uiValueCO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiValueCO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiValueCO2, 17);
    lv_obj_set_y(ui_uiValueCO2, 51);
    lv_obj_set_align(ui_uiValueCO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiValueCO2, "0.0");
    lv_obj_set_style_text_color(ui_uiValueCO2, lv_color_hex(0x17DD19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiValueCO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiValueCO2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelPPM = lv_label_create(ui_uiPannelLuxandCO2);
    lv_obj_set_width(ui_uiLabelPPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelPPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelPPM, 74);
    lv_obj_set_y(ui_uiLabelPPM, 51);
    lv_obj_set_align(ui_uiLabelPPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelPPM, "ppm");
    lv_obj_set_style_text_color(ui_uiLabelPPM, lv_color_hex(0x17DD19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelPPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelPPM, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelLux = lv_label_create(ui_uiPannelLuxandCO2);
    lv_obj_set_width(ui_uiLabelLux, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelLux, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelLux, 71);
    lv_obj_set_y(ui_uiLabelLux, -19);
    lv_obj_set_align(ui_uiLabelLux, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelLux, "lux");
    lv_obj_set_style_text_color(ui_uiLabelLux, lv_color_hex(0xDD6C17), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelLux, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelLux, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiImageLux = lv_img_create(ui_uiPannelLuxandCO2);
    lv_img_set_src(ui_uiImageLux, &ui_img_lux_icon_px_png);
    lv_obj_set_width(ui_uiImageLux, 80);
    lv_obj_set_height(ui_uiImageLux, 80);
    lv_obj_set_x(ui_uiImageLux, -49);
    lv_obj_set_y(ui_uiImageLux, -25);
    lv_obj_set_align(ui_uiImageLux, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiImageLux, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_uiImageLux, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiImageCO2 = lv_img_create(ui_uiPannelLuxandCO2);
    lv_img_set_src(ui_uiImageCO2, &ui_img_co2_icon_px_png);
    lv_obj_set_width(ui_uiImageCO2, 81);
    lv_obj_set_height(ui_uiImageCO2, 73);
    lv_obj_set_x(ui_uiImageCO2, -52);
    lv_obj_set_y(ui_uiImageCO2, 35);
    lv_obj_set_align(ui_uiImageCO2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiImageCO2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_uiImageCO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel5, 200);
    lv_obj_set_height(ui_Panel5, 185);
    lv_obj_set_x(ui_Panel5, -87);
    lv_obj_set_y(ui_Panel5, -59);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -1);
    lv_obj_set_y(ui_Label5, 76);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Fan");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x17DD19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_Panel5);
    lv_img_set_src(ui_Image10, &ui_img_fan_icon_2_px_png);
    lv_obj_set_width(ui_Image10, 133);
    lv_obj_set_height(ui_Image10, 122);
    lv_obj_set_x(ui_Image10, -14);
    lv_obj_set_y(ui_Image10, -21);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton3 = lv_imgbtn_create(ui_Panel5);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_icon_px_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_ImgButton3, 35);
    lv_obj_set_height(ui_ImgButton3, 35);
    lv_obj_set_x(ui_ImgButton3, 77);
    lv_obj_set_y(ui_ImgButton3, -66);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ImgButton3, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_uiPannelHumidandTemp = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_uiPannelHumidandTemp, 200);
    lv_obj_set_height(ui_uiPannelHumidandTemp, 185);
    lv_obj_set_x(ui_uiPannelHumidandTemp, -87);
    lv_obj_set_y(ui_uiPannelHumidandTemp, 132);
    lv_obj_set_align(ui_uiPannelHumidandTemp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiPannelHumidandTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiPannelHumidandTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiPannelHumidandTemp, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiPannelHumidandTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiValueTemp = lv_label_create(ui_uiPannelHumidandTemp);
    lv_obj_set_width(ui_uiValueTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiValueTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiValueTemp, 22);
    lv_obj_set_y(ui_uiValueTemp, 48);
    lv_obj_set_align(ui_uiValueTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiValueTemp, "00");
    lv_obj_set_style_text_color(ui_uiValueTemp, lv_color_hex(0xC01319), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiValueTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiValueTemp, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiValueHumid = lv_label_create(ui_uiPannelHumidandTemp);
    lv_obj_set_width(ui_uiValueHumid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiValueHumid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiValueHumid, 20);
    lv_obj_set_y(ui_uiValueHumid, -35);
    lv_obj_set_align(ui_uiValueHumid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiValueHumid, "00");
    lv_obj_set_style_text_color(ui_uiValueHumid, lv_color_hex(0x3C89E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiValueHumid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiValueHumid, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelHumid = lv_label_create(ui_uiPannelHumidandTemp);
    lv_obj_set_width(ui_uiLabelHumid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelHumid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelHumid, 63);
    lv_obj_set_y(ui_uiLabelHumid, -34);
    lv_obj_set_align(ui_uiLabelHumid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelHumid, "%");
    lv_obj_set_style_text_color(ui_uiLabelHumid, lv_color_hex(0x3C89E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelHumid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelHumid, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelTemp = lv_label_create(ui_uiPannelHumidandTemp);
    lv_obj_set_width(ui_uiLabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelTemp, 59);
    lv_obj_set_y(ui_uiLabelTemp, 50);
    lv_obj_set_align(ui_uiLabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelTemp, "°C");
    lv_obj_set_style_text_color(ui_uiLabelTemp, lv_color_hex(0xF4132A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelTemp, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiImageHumid = lv_img_create(ui_uiPannelHumidandTemp);
    lv_img_set_src(ui_uiImageHumid, &ui_img_humidity_icon_px_png);
    lv_obj_set_width(ui_uiImageHumid, 80);
    lv_obj_set_height(ui_uiImageHumid, 80);
    lv_obj_set_x(ui_uiImageHumid, -49);
    lv_obj_set_y(ui_uiImageHumid, -41);
    lv_obj_set_align(ui_uiImageHumid, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiImageHumid, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_uiImageHumid, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiImageTemp = lv_img_create(ui_uiPannelHumidandTemp);
    lv_img_set_src(ui_uiImageTemp, &ui_img_tempurate_2_px_png);
    lv_obj_set_width(ui_uiImageTemp, 80);
    lv_obj_set_height(ui_uiImageTemp, 80);
    lv_obj_set_x(ui_uiImageTemp, -47);
    lv_obj_set_y(ui_uiImageTemp, 47);
    lv_obj_set_align(ui_uiImageTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiImageTemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_uiImageTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiPannelWater = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_uiPannelWater, 200);
    lv_obj_set_height(ui_uiPannelWater, 185);
    lv_obj_set_x(ui_uiPannelWater, 118);
    lv_obj_set_y(ui_uiPannelWater, -59);
    lv_obj_set_align(ui_uiPannelWater, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiPannelWater, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiPannelWater, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiPannelWater, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiPannelWater, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_uiPannelWater, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_uiPannelWater, LV_BORDER_SIDE_NONE, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_uiLabelWater = lv_label_create(ui_uiPannelWater);
    lv_obj_set_width(ui_uiLabelWater, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelWater, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelWater, 8);
    lv_obj_set_y(ui_uiLabelWater, 76);
    lv_obj_set_align(ui_uiLabelWater, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelWater, "Water");
    lv_obj_set_style_text_color(ui_uiLabelWater, lv_color_hex(0x17DD19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelWater, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelWater, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiImageWater = lv_img_create(ui_uiPannelWater);
    lv_img_set_src(ui_uiImageWater, &ui_img_water_management_symbol_px_png);
    lv_obj_set_width(ui_uiImageWater, 110);
    lv_obj_set_height(ui_uiImageWater, 110);
    lv_obj_set_x(ui_uiImageWater, 1);
    lv_obj_set_y(ui_uiImageWater, -7);
    lv_obj_set_align(ui_uiImageWater, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiImageWater, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_uiImageWater, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiButtonWater = lv_imgbtn_create(ui_uiPannelWater);
    lv_imgbtn_set_src(ui_uiButtonWater, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_button_icon_px_png, NULL);
    lv_imgbtn_set_src(ui_uiButtonWater, LV_IMGBTN_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_uiButtonWater, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_uiButtonWater, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_uiButtonWater, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_uiButtonWater, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_width(ui_uiButtonWater, 35);
    lv_obj_set_height(ui_uiButtonWater, 35);
    lv_obj_set_x(ui_uiButtonWater, 78);
    lv_obj_set_y(ui_uiButtonWater, -65);
    lv_obj_set_align(ui_uiButtonWater, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiButtonWater, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_uiPannelSoild = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_uiPannelSoild, 200);
    lv_obj_set_height(ui_uiPannelSoild, 185);
    lv_obj_set_x(ui_uiPannelSoild, 118);
    lv_obj_set_y(ui_uiPannelSoild, 132);
    lv_obj_set_align(ui_uiPannelSoild, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_uiPannelSoild, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiPannelSoild, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiPannelSoild, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiPannelSoild, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiValueSoild = lv_label_create(ui_uiPannelSoild);
    lv_obj_set_width(ui_uiValueSoild, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiValueSoild, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiValueSoild, -14);
    lv_obj_set_y(ui_uiValueSoild, 61);
    lv_obj_set_align(ui_uiValueSoild, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiValueSoild, "00");
    lv_obj_set_style_text_color(ui_uiValueSoild, lv_color_hex(0x3C89E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiValueSoild, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiValueSoild, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiLabelSoild = lv_label_create(ui_uiPannelSoild);
    lv_obj_set_width(ui_uiLabelSoild, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiLabelSoild, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiLabelSoild, 27);
    lv_obj_set_y(ui_uiLabelSoild, 61);
    lv_obj_set_align(ui_uiLabelSoild, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiLabelSoild, "%");
    lv_obj_set_style_text_color(ui_uiLabelSoild, lv_color_hex(0x3C89E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiLabelSoild, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiLabelSoild, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiImageSoild = lv_img_create(ui_uiPannelSoild);
    lv_img_set_src(ui_uiImageSoild, &ui_img_hummid_soild_icon_px_png);
    lv_obj_set_width(ui_uiImageSoild, 110);
    lv_obj_set_height(ui_uiImageSoild, 110);
    lv_obj_set_x(ui_uiImageSoild, -2);
    lv_obj_set_y(ui_uiImageSoild, -26);
    lv_obj_set_align(ui_uiImageSoild, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiImageSoild, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_uiImageSoild, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uiPannelTerminal = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_uiPannelTerminal, 170);
    lv_obj_set_height(ui_uiPannelTerminal, 376);
    lv_obj_set_x(ui_uiPannelTerminal, 310);
    lv_obj_set_y(ui_uiPannelTerminal, 38);
    lv_obj_set_align(ui_uiPannelTerminal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiPannelTerminal, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_uiPannelTerminal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiPannelTerminal, lv_color_hex(0x160A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiPannelTerminal, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uiPannelTerminal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiPannelTerminal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiPannelTerminal, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiTextTerminal = lv_textarea_create(ui_uiPannelTerminal);
    lv_obj_set_width(ui_uiTextTerminal, lv_pct(130));
    lv_obj_set_height(ui_uiTextTerminal, lv_pct(112));
    lv_obj_set_y(ui_uiTextTerminal, -1);
    lv_obj_set_x(ui_uiTextTerminal, lv_pct(0));
    lv_obj_set_align(ui_uiTextTerminal, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_uiTextTerminal, "Placeholder...");
    lv_obj_clear_flag(ui_uiTextTerminal, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_border_color(ui_uiTextTerminal, lv_color_hex(0x00FF66), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiTextTerminal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiTextTerminal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_uiTerminal, ui_event_uiTerminal, LV_EVENT_ALL, NULL);
    uic_uiPannelBackgound = ui_uiPannelBackgound;
    uic_uiPannelSolgan = ui_uiPannelSolgan;
    uic_uiLogoPtit = ui_uiLogoPtit;
    uic_uiIlovePtit = ui_uiIlovePtit;
    uic_uiIhatePtit = ui_uiIhatePtit;
    uic_uiTerminal = ui_uiTerminal;
    uic_uiPannelLight = ui_uiPannelLight;
    uic_uiLabelLight = ui_uiLabelLight;
    uic_uiImageLight = ui_uiImageLight;
    uic_uiButtonLight = ui_uiButtonLight;
    uic_uiPannelLuxandCO2 = ui_uiPannelLuxandCO2;
    uic_uiValueLux = ui_uiValueLux;
    uic_uiValueCO2 = ui_uiValueCO2;
    uic_uiLabelPPM = ui_uiLabelPPM;
    uic_uiLabelLux = ui_uiLabelLux;
    uic_uiImageLux = ui_uiImageLux;
    uic_uiImageCO2 = ui_uiImageCO2;
    uic_uiPannelHumidandTemp = ui_uiPannelHumidandTemp;
    uic_uiValueTemp = ui_uiValueTemp;
    uic_uiValueHumid = ui_uiValueHumid;
    uic_uiLabelHumid = ui_uiLabelHumid;
    uic_uiLabelTemp = ui_uiLabelTemp;
    uic_uiImageHumid = ui_uiImageHumid;
    uic_uiImageTemp = ui_uiImageTemp;
    uic_uiPannelWater = ui_uiPannelWater;
    uic_uiButtonWater = ui_uiButtonWater;
    uic_uiPannelSoild = ui_uiPannelSoild;
    uic_uiValueSoild = ui_uiValueSoild;
    uic_uiLabelSoild = ui_uiLabelSoild;
    uic_uiImageSoild = ui_uiImageSoild;
    uic_uiTextTerminal = ui_uiTextTerminal;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_uiPannelBackgound = NULL;
    ui_uiPannelBackgound = NULL;
    uic_uiPannelSolgan = NULL;
    ui_uiPannelSolgan = NULL;
    uic_uiLogoPtit = NULL;
    ui_uiLogoPtit = NULL;
    uic_uiIlovePtit = NULL;
    ui_uiIlovePtit = NULL;
    uic_uiIhatePtit = NULL;
    ui_uiIhatePtit = NULL;
    uic_uiTerminal = NULL;
    ui_uiTerminal = NULL;
    uic_uiPannelLight = NULL;
    ui_uiPannelLight = NULL;
    uic_uiLabelLight = NULL;
    ui_uiLabelLight = NULL;
    uic_uiImageLight = NULL;
    ui_uiImageLight = NULL;
    uic_uiButtonLight = NULL;
    ui_uiButtonLight = NULL;
    uic_uiPannelLuxandCO2 = NULL;
    ui_uiPannelLuxandCO2 = NULL;
    uic_uiValueLux = NULL;
    ui_uiValueLux = NULL;
    uic_uiValueCO2 = NULL;
    ui_uiValueCO2 = NULL;
    uic_uiLabelPPM = NULL;
    ui_uiLabelPPM = NULL;
    uic_uiLabelLux = NULL;
    ui_uiLabelLux = NULL;
    uic_uiImageLux = NULL;
    ui_uiImageLux = NULL;
    uic_uiImageCO2 = NULL;
    ui_uiImageCO2 = NULL;
    ui_Panel5 = NULL;
    ui_Label5 = NULL;
    ui_Image10 = NULL;
    ui_ImgButton3 = NULL;
    uic_uiPannelHumidandTemp = NULL;
    ui_uiPannelHumidandTemp = NULL;
    uic_uiValueTemp = NULL;
    ui_uiValueTemp = NULL;
    uic_uiValueHumid = NULL;
    ui_uiValueHumid = NULL;
    uic_uiLabelHumid = NULL;
    ui_uiLabelHumid = NULL;
    uic_uiLabelTemp = NULL;
    ui_uiLabelTemp = NULL;
    uic_uiImageHumid = NULL;
    ui_uiImageHumid = NULL;
    uic_uiImageTemp = NULL;
    ui_uiImageTemp = NULL;
    uic_uiPannelWater = NULL;
    ui_uiPannelWater = NULL;
    ui_uiLabelWater = NULL;
    ui_uiImageWater = NULL;
    uic_uiButtonWater = NULL;
    ui_uiButtonWater = NULL;
    uic_uiPannelSoild = NULL;
    ui_uiPannelSoild = NULL;
    uic_uiValueSoild = NULL;
    ui_uiValueSoild = NULL;
    uic_uiLabelSoild = NULL;
    ui_uiLabelSoild = NULL;
    uic_uiImageSoild = NULL;
    ui_uiImageSoild = NULL;
    ui_uiPannelTerminal = NULL;
    uic_uiTextTerminal = NULL;
    ui_uiTextTerminal = NULL;

}
